"use client";

import React from "react";
import { PageContainer } from "@/components/ui/page-container";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { FileText, Download } from "lucide-react";
import { downloadCSV } from "@/utils/csv";
import { toast } from "sonner";

export default function FinancialReportsPage() {
  const reports = [
    { 
      title: "Monthly Revenue Report", 
      description: "Detailed breakdown of revenue by tenant for the current month", 
      date: "June 2026", 
      type: "PDF",
      data: [
        { Parameter: "Total Monthly Revenue", Value: "$261,500" },
        { Parameter: "Subscription Revenue", Value: "$245,000" },
        { Parameter: "Overage Billing", Value: "$12,300" },
        { Parameter: "Add-on Packages", Value: "$4,200" }
      ]
    },
    { 
      title: "Outstanding Collections", 
      description: "List of all unpaid and overdue invoices across the platform", 
      date: "June 2026", 
      type: "Excel",
      data: [
        { InvoiceID: "INV-2026-4122", Tenant: "CareFirst Clinics", AmountDue: "$1,200", DaysOverdue: 14 },
        { InvoiceID: "INV-2026-5831", Tenant: "Apex Hospital Group", AmountDue: "$4,500", DaysOverdue: 3 },
        { InvoiceID: "INV-2026-9281", Tenant: "HealthOne Group", AmountDue: "$850", DaysOverdue: 30 }
      ]
    },
    { 
      title: "Insurance Claims Summary", 
      description: "Analytics on claim approval rates and processing times", 
      date: "Q2 2026", 
      type: "PDF",
      data: [
        { Network: "BlueCross BlueShield", ClaimsProcessed: 1240, ApprovalRate: "94.2%", AverageProcessingDays: 12 },
        { Network: "Aetna Health", ClaimsProcessed: 880, ApprovalRate: "91.5%", AverageProcessingDays: 14 },
        { Network: "Government PMJAY", ClaimsProcessed: 3200, ApprovalRate: "88.0%", AverageProcessingDays: 18 }
      ]
    },
    { 
      title: "Subscription Churn Report", 
      description: "Analysis of tenant subscriptions, renewals, and cancellations", 
      date: "Year to Date", 
      type: "Excel",
      data: [
        { PlanTier: "Enterprise Plan", ActiveTenants: 14, RenewalsThisMonth: 3, CancellationsYTD: 0 },
        { PlanTier: "Professional Plan", ActiveTenants: 48, RenewalsThisMonth: 12, CancellationsYTD: 2 },
        { PlanTier: "Starter Plan", ActiveTenants: 92, RenewalsThisMonth: 22, CancellationsYTD: 5 }
      ]
    },
  ];

  const handleDownload = (report: typeof reports[number]) => {
    downloadCSV(report.data, `${report.title.toLowerCase().replace(/\s+/g, '-')}.csv`);
    toast.success(`${report.title} downloaded successfully.`);
  };

  const handleGenerateCustom = () => {
    const customData = [
      { Metric: "Custom Interval Revenue", Value: "$124,500" },
      { Metric: "Generated By", Value: "Super Admin Console" },
      { Metric: "Timestamp", Value: new Date().toLocaleString() }
    ];
    downloadCSV(customData, "custom-financial-extract.csv");
    toast.success("Custom financial report generated and downloaded.");
  };

  return (
    <PageContainer>
      <PageHeader
        title="Financial Reports"
        description="Generate and view financial reports and analytics"
        actions={
          <Button onClick={handleGenerateCustom}>
            <FileText className="mr-2 h-4 w-4" />
            Generate Custom Report
          </Button>
        }
      />
      
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 mt-6">
        {reports.map((report, index) => (
          <div key={index} className="flex flex-col bg-card border border-border p-6 rounded-xl hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-4">
              <h3 className="text-lg font-semibold text-foreground">{report.title}</h3>
              <span className="text-xs font-medium px-2 py-1 bg-muted text-muted-foreground rounded">{report.type}</span>
            </div>
            <p className="text-sm text-muted-foreground mb-6 flex-1">{report.description}</p>
            <div className="flex items-center justify-between border-t border-border pt-4">
              <span className="text-xs text-muted-foreground">Period: {report.date}</span>
              <Button variant="ghost" size="sm" onClick={() => handleDownload(report)}>
                <Download className="mr-2 h-4 w-4" />
                Download
              </Button>
            </div>
          </div>
        ))}
      </div>
    </PageContainer>
  );
}
