export const ROUTES = {
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  tenants: "/tenants",
  hospitals: "/hospitals",
  branches: "/branches",
  departments: "/departments",
  users: "/users",
  roles: "/roles",
  permissions: "/permissions",
  doctors: "/doctors",
  patients: "/patients",
  revenue: "/revenue",
  notifications: "/notifications",
  integrations: "/integrations",
  monitoring: "/monitoring",
  audit: "/audit",
  reports: "/reports",
  settings: "/settings",
};
